### ISSUE TITLE
Lexicometry roadmap

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/xan#249]
Use-cases:

- [ ] top-k relevant token percolations
- [ ] inverted indices
- [ ] vectorization

Todo:

- [x] Bench in-process token filters vs. piping
- [x] Bench in-process vocab creation vs. piping into frequencies
- [ ] Add `vocab` command with idf, chi2, pmi
- [ ] Gf idf
- [ ] ctfidf
- [ ] Skip grams
- [x] Add `--ngrams` to tokenizer
- [x] Add `top` aggregator
- [ ] Add `argtop` aggregator
- [ ] Add example about merging vocabularies
- [ ] Add example with tee to produce vocabulary
- [ ] `vocab --doc` idf, bm25, chi2, tf, tfidf
- [ ] tf ratios and df ratios, probability of token happening
- [ ] Chi2 of tfidf
- [ ] Pigeonhole can work in doc-token context?
- [ ] cooc variant of vocab with pmi and and pigeonholing npmi and collocations
- [x] Make a subcommand of doc/cooc rather

Notes:

- An `idf` aggregator is cumbersome because it needs to know the number of groups, so it's 1. not generic and 2. cannot work with `groupby --sorted`.
- Take k1 = 1.2 and b = 0.75
- Stemmers and fingerprinting
- chi2 for doc-token: (tf - etf)^2 / etf, where etf = ?, link with pigeonhole or just random probability? how to normalise?

References:

- https://kmwllc.com/index.php/2020/03/20/understanding-tf-idf-and-bm-25/
- https://github.com/gersonUrban/find_best_words_with_chi2
- https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-similarity.html#bm25

**Comment by Yomguithereal** [comment]
- [ ] lexicometrie
- [ ] inverted index
- [ ] vectorisation
